name: Docker push on master

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      word: ${{ steps.needed_step.outputs.word }}
    steps:
      - name: Needed step
        id: needed_step
        run: echo "12345"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      TAG1: default
      TAG2: ${{ needs.job1.outputs.word }}
    strategy:
      matrix:
        tag: [$TAG1, $TAG2]
    steps:
      - name: Print
        run: echo "${{ matrix.tag }}"
