name: Docker push on master

on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker
        run: |
          apt list | grep docker
          sudo apt-get install docker-ce -y
          docker version

      - name: Test docker
        run: docker version
