name: Docker push on master

on: push

jobs:

  build-push-test:

      runs-on: ubuntu-latest
      timeout-minutes: 1440
      env:
        IMAGE_NAME: autoware/model-zoo-tvm-cli-test
        TAG_NAME: bleedingedge

      steps:

        - name: Checkout
          uses: actions/checkout@v2

        - name: arm64 image build
          run: |
            # Build image
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --use --name buildkit-builder --platform linux/amd64,linux/arm64
            uname -a
            cat /proc/sys/fs/binfmt_misc/qemu-*
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx ls
            docker buildx inspect buildkit-builder
            ./scripts/tvm_cli/build.sh -i "$IMAGE_NAME" -t "$TAG_NAME" --platform arm64

        - name: arm64 image run
          run: docker run "$IMAGE_NAME":"$TAG_NAME"