name: Docker push on master

on:
  push:
    branches:
      - master
    paths:
      - 'scripts/tvm_cli/**'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      word: ${{ steps.needed_step.outputs.word }}
    steps:
      - name: Needed step
        id: needed_step
        run: echo "12345"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix:
        tag: [default, ${{ needs.job1.outputs.word }}]
    steps:
      - name: Print
        run: echo "${{ matrix.tag }}"