name: Docker push on master

on: push

jobs:
  job:
    runs-on: ARM64
    steps:
      - name: Install docker
        run: sudo apt-get install docker

      - name: Test docker
        run: docker version
