name: Contribution pull requests validation

on:
  pull_request:

jobs:

  setup-lfs-arm64:
      runs-on: ARM64

      steps:
        - name: Install LFS
          run: sudo apt-get install -y git-lfs

  tvm-cli-validate:
      needs: setup-lfs-arm64

      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, ARM64]

      container:
        image: autoware/model-zoo-tvm-cli:bleedingedge

      steps:

        - name: Checkout
          uses: actions/checkout@v1
          with:
            lfs: true

        - name: tvm_cli test
          run: |
            cp -r . /tmp
            ./scripts/tvm_cli/tvm_cli.py test
